site_name: UAB Research Computing DevOps Docs
repo_url: https://github.com/uabrc/devops-docs

theme:
  name: material
  search_index_only: true
  custom_dir: theme
  language: en
  features:
    - navigation.indexes
    - navigation.instant

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2021-2022 The University of Alabama at Birmingham.<br /><b>Still stuck after reading?</b> Email us at <a href="mailto:support@listserv.uab.edu" class="supportemail">support@listserv.uab.edu</a>

markdown_extensions:
  - admonition
  - attr_list
  - lightgallery:
      show_description_in_lightgallery: true
      show_description_as_inline_caption: false
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - table-reader:
      data_path: docs
  - git-revision-date-localized:
      type: date
  - redirects:
      redirect_maps:

nav:
  - Home: index.md
